- developer_docs/docker-image.md
- developer_docs/helm-chart.md
Please take a pull request and merge into develop branch for IBM repo
> Issue Fix for changes in doc 

- src/main/java/com/ibm/nfvodriver/driver/impl/NexusNSPackageRepositoryDriver.java
- src/main/java/com/ibm/nfvodriver/model/web/ErrorInfo.java
- src/main/java/com/ibm/nfvodriver/web/alm/ALMExceptionHandlingControllerAdvice.java
- src/main/java/com/ibm/nfvodriver/web/alm/AvailabilityController.java
- src/main/java/com/ibm/nfvodriver/web/alm/LifecycleController.java
- src/main/java/com/ibm/nfvodriver/web/alm/NotImplementedException.java
- src/test/java/com/ibm/nfvodriver/driver/impl/NexusNsPackageRepositoryDriverTest.java
- src/test/java/com/ibm/nfvodriver/web/alm/AvailabilityControllerTest.java
- src/test/java/com/ibm/nfvodriver/web/alm/LifecycleControllerTest.java
> Worked on uncommented Junits and added a comment

- src/main/java/com/ibm/nfvodriver/driver/NSLifecycleManagementDriver.java
- src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
Hi @lokanalla .
I have created PR for issue #13 and #3481[TNC], .Please review and let me know any changes required .
Thanks 
Prasad S
> Sol003 drive delete lifecycle delete method code change

- developer_docs/release.md
> Added Release document

- pom.xml
- src/main/resources/helm/sol005-lifecycle-driver/Chart.yaml
Hi @lokanalla 
Fix issue #3529 [TNC], Raised PR and please review code .
Thanks 
Prasad S
>  Docker image with helm package issue fix

- developer_docs/release.md
- pom.xml
- src/main/resources/helm/sol005-lifecycle-driver/Chart.yaml
Release 0.0.1 after fixing docker and helm package issue
> Release 0.0.1 after fixing docker and helm package issue

- pom.xml
- src/main/resources/docker/Dockerfile
Issue: https://github.com/IBM/sol005-lifecycle-driver/issues/20
Description of the changes: https://github.com/IBM/sol005-lifecycle-driver/issues/20
List of related PRs. : None
Project builds without any errors.
Unit Tests updated (or created where needed) and all pass.
You have ran manual functional “smoke” test (does product as a whole still work?).
User Story meets the acceptance criteria - and passes. acceptance criteria should be understood at outset.
There is a PR for update of internal documentation for the affected Project(s) - README etc.
> Sol005 driver- Drivers vulnerabilities fixes

- src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
Issue: https://github.com/IBM/sol005-lifecycle-driver/issues/22
Description of the changes: https://github.com/IBM/sol005-lifecycle-driver/issues/22
List of related PRs. : None
Project builds without any errors.
Unit Tests updated (or created where needed) and all pass.
You have ran manual functional “smoke” test (does product as a whole still work?).
User Story meets the acceptance criteria - and passes. acceptance criteria should be understood at outset.
There is a PR for update of internal documentation for the affected Project(s) - README etc.
> Adding ScaleIn & ScaleOut lifecycle

- src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
> Modifying UpdateLifeCycleName to Upgrade for SOL005 driver

- docs/ConfiguringKafka.md
- src/main/resources/config/application-kubernetes.yml
> Kafka instance name changes in SOL005 driver

- docs/ConfiguringKafka.md
- docs/Installation.md
- src/main/resources/config/application-kubernetes.yml
- src/main/resources/helm/sol005-lifecycle-driver/values.yaml
> ImageRepo changes in values.yaml and kakfa instance changes

- CONTRIBUTING.md
> Contributor GitHub Id changes in Contributing.md

- src/main/resources/helm/sol005-lifecycle-driver/values.yaml
> modifying icr.io path

- src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
Issue: #42 
Description of the changes: #42 
List of related PRs. : None
Project builds without any errors.
Unit Tests updated (or created where needed) and all pass.
You have ran manual functional “smoke” test (does product as a whole still work?).
User Story meets the acceptance criteria - and passes. acceptance criteria should be understood at outset.
There is a PR for update of internal documentation for the affected Project(s) - README etc.
> Change lifecycle name from Scale to ScaleToLevel

- pom.xml
> Vulnerabilites fixes for sol005 driver

- src/main/java/com/ibm/nfvodriver/config/WebSecurityConfiguration.java
> Resricting all  /management API calls excluding /info and /health from unauthenticated access.

- pom.xml
Release activity for after vulnerabilities fixes.
> Release activity

- src/main/java/com/ibm/common/utils/LoggingUtils.java
- src/main/java/com/ibm/nfvodriver/driver/NSLifecycleManagementDriver.java
- src/main/java/com/ibm/nfvodriver/model/MessageDirection.java
- src/main/java/com/ibm/nfvodriver/model/MessageType.java
- src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
- src/test/java/com/ibm/nfvodriver/driver/NSLifecycleManagementDriverTest.java
- src/test/java/com/ibm/nfvodriver/service/LifecycleManagementServiceTest.java
- src/test/java/com/ibm/nfvodriver/test/TestConstants.java
#62 
Enable Request Response Logging
Signed-off-by: rkumar8j
> Enable Request Response Logging

- docs/Installation.md
Signed-off-by: Prasad Settipalli <prasad.settipalli@ibm.com>
Fixe #65for [TNC] #4841
> Documentation changes for Onboarding the drivers wrt CP4NA versions for sol005-lifecycle-driver

- pom.xml
#70
SNAPSHOT version update
Signed-off-by: rkumar8j
> SNAPSHOT version update

- docs/Installation.md
#77 
Add documentation for ssl.
Signed-off-by: Haynes Davis <Haynes.Davis@ibm.com>
> Add ssl retaled documentation

- CHANGELOG.md
CHANGELOG for release version 0.2.0
Signed-off-by: Ranjeet Kumar [rkumar8j@in.ibm.com](mailto:rkumar8j@in.ibm.com)
> CHANGELOG for release version 0.2.0

- CHANGELOG.md
> Spell correction

- CHANGELOG.md
> Correction in changelog

- src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
- src/main/java/com/ibm/nfvodriver/utils/Constants.java
#88
Add switch case and reusable functions 
Signed-off-by: rkumar8j (mailto:rkumar8j@in.ibm.com)
> Adding switch case and reusable function

- CHANGELOG.md
- pom.xml
CHANGELOG file update for release activity 0.2.1
> Release activity 0.2.1

- CHANGELOG.md
- pom.xml
> CHANGELOG file update for release-0.3.0

- src/main/resources/helm/sol005-lifecycle-driver/Chart.yaml
> Adding appVersion in chart.yaml

- src/main/java/com/ibm/nfvodriver/driver/NSDManagementDriver.java
#98
Optimize the construction of HttpRequest entity- NSDManagementDriver.java
> sol005 code optimization

- pom.xml
#104
Bug Fix- Springboot Upgrade
> Bug Fix- Springboot Upgrade

- CHANGELOG.md
- pom.xml
release activity for cp4na-2.4.1
> release activity for cp4na-2.4.1

- src/main/resources/logback-spring.xml
#108
Fix to discard unwanted springboot security logs
> Fix to discard unwanted springboot security logs

- pom.xml
> adding spring security core in pom.xml

- CHANGELOG.md
- pom.xml
> Release activity for CP4NA-2.4.2

- pom.xml
> Post release activity

- docs/AddingDeploymentLocation.md
- src/main/java/com/ibm/nfvodriver/driver/NSLifecycleManagementDriver.java
- src/main/java/com/ibm/nfvodriver/service/impl/LcmOpOccPollingService.java
- src/main/java/com/ibm/nfvodriver/utils/RequestResponseLogUtils.java
- src/main/java/com/ibm/nfvodriver/web/etsi/LifecycleNotificationController.java
- src/test/java/com/ibm/nfvodriver/driver/NSLifecycleManagementDriverTest.java
> Issue#115 Logging issues and doc changes for notification url

- developer_docs/release.md
> updated the release.md to use prod profile

- pom.xml
1. Updated pom.xml to use spring boot 2.7.8. 
2. Updated commons-io version to 2.11.0
3. Added commons-net dependency to fix vulnerability
> updated versions to fix vulnerabilities

- pom.xml
1. Updated pom.xml to use spring boot 2.7.10. 
2. Updated snakeyml version to 2.0
> fixed security vulnerabilities after updated spring boot and snakeyml

- CHANGELOG.md
- pom.xml
- src/main/java/com/ibm/nfvodriver/driver/NSLifecycleManagementDriver.java
- src/main/java/com/ibm/nfvodriver/web/etsi/LifecycleNotificationController.java
merge develop -> master for release 0.3.1-RC1
> merge develop -> master for release 0.3.1-RC1

- pom.xml
> updated spring boot to fix vulnerabilities

- CHANGELOG.md
- pom.xml
Merge develop to master for pre-release 0.3.2-RC1
> Merge develop to master for pre-release 0.3.2-RC1

- pom.xml
Merge develop to master for releasing version 0.3.2
> Merge develop to master for releasing version 0.3.2

- CONTRIBUTING.md
- developer_docs/release.md
Will merge once branch is renamed
> Rename to main - references update

- CHANGELOG.md
- CONTRIBUTING.md
- developer_docs/release.md
- pom.xml
merge develop->main for release 0.3.3-RC1
> merge develop->main for release 0.3.3-RC1

- CHANGELOG.md
- pom.xml
Merge develop->main for release v0.3.3
> Merge develop->main for release v0.3.3

- pom.xml
> fixes vulnerabilities

- CHANGELOG.md
- pom.xml
Merge develop->main to release 0.3.5
> Merge develop->main to release 0.3.5

- pom.xml
> Removed duplicate entry of dependency from pom.xml

- CHANGELOG.md
merge develop->main branch for release 0.4.0 after fixing bug 150
> merge develop->main branch for release 0.4.0 after fixing bug 150

- pom.xml
> Fix build issue

- pom.xml
merge develop->main branch for release 0.4.0 after fixing pipeline issue
> merge develop->main branch for release 0.4.0 after fixing pipeline issue
